-
  name: Deploy a web application
  hosts: vm2_server
  become: yes
  vars:
    db_name: employee_db
    db_user: db_user
    db_password: Passw0rd
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes

    - name: Install dependencies
      apt: name={{ item }} state=present
      with_items:
       - python3
       - python3-setuptools
       - python3-dev
       - build-essential
       - python3-pip
       - python3-mysqldb

    - name: Install MySQL database
      apt:
        name: "{{ item }}"
        state:  present
      with_items:
       - mysql-server
       - mysql-client

    - name: Start Mysql Service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create Application Database
      mysql_db: name={{ db_name }} state=present

    - name: Create Application DB User
      mysql_user: name={{ db_user }} password={{ db_password }} priv='*.*:ALL' host='%' state='present'

    - name: Ensure venv module is installed
      apt:
        name: python3-venv
        state: present
      become: yes

    - name: Create a virtual environment
      command: python3 -m venv /opt/myenv
      args:
        creates: /opt/myenv

    - name: Install Python packages in the virtual environment
      command: /opt/myenv/bin/pip install {{ item }}
      loop:
        - flask
        - flask-mysql


    - name: Copy web-server code
      copy: src=app.py dest=/opt/app.py

    - name: Start web-application
      shell: FLASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 &

